### ISSUE TITLE
bpImageConverterC_CopyBlock for Doubles

### ISSUE THREAD

**Issue by MattHazard** [imaris/ImarisWriter#3]
Is it possible to have support for Doubles in the C Interface for the bpImageConverterC_CopyBlock method? It looks like there is already support for it in the C++ interface but I do not see a way of doing it in C unless there is something I am missing.

**Comment by MattHazard** [comment]
To add to this, I suppose bpConverterTypesC_DoubleType would also need to be added to the bpConverterTypesC_DataType enum as well.

**Comment by imaris** [comment]
Hallo Matt, the library do _not_ support doubles at the moment, mainly because Imaris cannot open images in that format. There is a type definition for doubles in C++, but the library does not support all types defined in tDataType, only uint8, unint16, uint32 and float (note that uint32 images are currently not supported by Imaris). For the programmers: This is according to the explicit template instantiations of bpImageConverter and several others, which may be extended. The library needs modifications to support doubles and it will arguably provide little value since Imaris cannot open such images.
Bests, Igor

**Comment by MattHazard** [comment]
Thank you for the information.
